name: Deploy Bicep to Azure

on:
  workflow_dispatch:

jobs:
  what-if:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Azure PowerShell
        uses: azure/powershell@v1
        with:
          azPSVersion: 'latest'

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          allow-no-subscriptions: true

      - name: Run What-If deployment
        run: |
          az deployment group what-if --resource-group myResourceGroup --template-file main.bicep

  deploy:
    runs-on: ubuntu-latest
    needs: what-if

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Azure PowerShell
        uses: azure/powershell@v1
        with:
          azPSVersion: 'latest'

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          allow-no-subscriptions: true

      - name: Run deploy.bicep script
        run: |
          pwsh deploy.bicep
